# Data Preprocessing

## Importing the libraries

In [140]:
import numpy as np
#numpy: collection of high-level mathematical functions to operate.
import matplotlib.pyplot as plt
#matplotlib: plotting lib for python and its numerical mathematics extension NumPy.
import pandas as pd
#pandas: for data manipulation and analysis.

## Importing the dataset

In [153]:
dataset = pd.read_csv('Data.csv')

#create 2 new entities 
#(features(independent var, usually left), dependent var(to predict))
X = dataset.iloc[:, :-1].values
#iloc: locate indexes. Extract indexes from the data set. iloc[row, col]
#: all the rows/cols. :-1 minus means last col in Python.

Y = dataset.iloc[:, -1].values


In [154]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [155]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [156]:
#import scikit-learn library that features various classification, regression and clustering algorithms.
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
#missing_values: default 값은 np.nan으로 비어있는 값을 채우고 
#strategy: 채울 값에 대한 함수로 디폴트 파라미터 값은 mean 즉, 산술평균값이 됩니다.

#only numeric value(No string)
#fit(): look for all the missing vals in age/salary cols.
imputer.fit(X[:, 1:3])

#transform(): replace the missing sal/age by the mean value.
#transform returns new version of the matrix features X. So update required.
X[:, 1:3] = imputer.transform(X[:, 1:3])


In [157]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [158]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#ColumnTransformer() two arguements: 
    #transformers (specify what kind of transformation wanted, which indexes of the col to transform)
    #remainder (specify to keep the cols that won't be applied some transformations meaning age/salary)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])] , remainder='passthrough')
#transformers = [(kind of transformation, kind of encoding, indexes of the cols want to encode(first col = 0)]

#fit_transform(): transforms data strings into ints.
#fit_transform doesn't return the output as a non array and X is an numpy array.
#Therefore, we need to force the output of this to be an numpy array.
X = np.array(ct.fit_transform(X))

In [159]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [161]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [165]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [194]:
from sklearn.model_selection import train_test_split

#train_test_split( dataset X,Y, split size: test size 20%, random_state = 1 is to get the same
# split and therefore the same training set.)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [195]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [196]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [197]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [198]:
print(Y_test)

[0 1]


## Feature Scaling

In [200]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#do we have to apply feature scaling standardization to the dummy variables? NO.
#will lose the interpretation and will not improve training performance at all.

#only do standardization on age, salary cols.
#age col index of X_train is 3, salary is 4.
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

#test dataset is new data => only apply the transform method(no fit method)
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [201]:
print(X_train)
#new values bewteen -2 and +2 (ages and salary)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [202]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
